before_install:
  - git clone --recursive https://github.com/rust-lang/cargo

install:
  - curl http://www.rust-lang.org/rustup.sh | sudo sh -
  - cd cargo && make && sudo make install && cd .. && sudo rm -rf cargo

script:
  - cargo build

branches:
  only: master
